//! THE DIAGNOSTIC BUNDLE — what a church can send when something went wrong.
//!
//! Single responsibility: compose one text file describing this machine and this
//! installation, containing nothing that belongs to the church.
//!
//! ## Why a file and not a screen
//!
//! Settings → Diagnostics has shown the right facts for a while, and it has been
//! useless for the purpose it exists for: an operator cannot email a screen. What
//! actually happens is somebody photographs it with a phone, which loses half the
//! table and all of the latency history, or reads numbers aloud over the phone.
//!
//! ## The allow-list, and why it is an allow-list
//!
//! This file is *for sending*. It is the one artefact in Relay that is expected to
//! leave the building, so it is composed by naming every field that may be in it —
//! never by naming the fields to strip.
//!
//! `telemetry.rs` learned this the expensive way: its doc comment said "deliberately
//! an ALLOW-LIST … a blocklist fails open, and the cost of failing open here is
//! publishing somebody's sermon", and the implementation underneath was a blocklist
//! that shipped every field it had not thought of. **A blocklist here would leak
//! whatever the next feature adds**, and by then nobody would be reading this file.
//!
//! So: no transcript, no verse text, no lyric, no announcement, no service title, no
//! plan name, no song name, no template name, no media filename. Counts, versions,
//! timings, states and the operator's own configuration choices — nothing else.
//!
//! ## Home directories are personal too
//!
//! `/Users/ada/Library/Application Support/com.relay.app` names a person. Every path
//! in this file is written relative to `~`, and `scrub_paths` is applied to
//! everything on the way out rather than at each call site — because the call site
//! that forgets is the one that ships someone's full name to a stranger.

use crate::db;

/// Replace the user's home directory with `~`, wherever it appears.
///
/// Applied to the WHOLE document at the end, not per field. A per-field version is
/// one forgotten call away from a leak, and this costs one pass over a few kilobytes.
pub fn scrub_paths(text: &str, home: Option<&str>) -> String {
    let mut out = text.to_string();
    if let Some(h) = home.filter(|h| h.len() > 3) {
        out = out.replace(h, "~");
        // Windows paths arrive with either separator depending on who built the
        // string, and a half-scrubbed path still names the person.
        out = out.replace(&h.replace('\\', "/"), "~");
    }
    out
}

/// One line of the bundle: a label and a value that is safe to send.
///
/// The label owns its string. It started out `&'static str`, which forced a call
/// site holding an operator-chosen screen name to `Box::leak` it — a leak per screen
/// per export, to satisfy a lifetime nobody needed.
pub struct Fact(pub String, pub String);

impl Fact {
    pub fn new(key: impl Into<String>, value: impl Into<String>) -> Self {
        Fact(key.into(), value.into())
    }
}

/// Compose the bundle.
///
/// Takes its facts as arguments rather than reaching for them, so the whole
/// document can be tested — including, and especially, the test that asserts what
/// is NOT in it.
pub fn compose(sections: &[(&str, Vec<Fact>)]) -> String {
    let mut md = String::new();
    md.push_str("# Relay diagnostic report\n\n");
    md.push_str(
        "This file describes the app and this machine. It deliberately contains **no \
         transcript, no verse text, no song lyric, no announcement and no service, plan or \
         song names** — nothing that belongs to your church. Paths are shortened to `~` so \
         it does not name anybody.\n\n",
    );
    for (title, facts) in sections {
        md.push_str(&format!("## {title}\n\n"));
        if facts.is_empty() {
            md.push_str("_Nothing to report._\n\n");
            continue;
        }
        for Fact(k, v) in facts {
            md.push_str(&format!("- **{k}:** {v}\n"));
        }
        md.push('\n');
    }
    md.push_str(
        "---\n\n_Generated by Relay. If you were asked for this file, send it as it is — \
         editing it usually removes the part that explains the problem._\n",
    );
    md
}

/// Where the bundle is written. Downloads if there is one, app-data otherwise —
/// exporting must never depend on the shape of somebody's home directory.
pub fn write_bundle(body: &str, stamp: &str) -> std::io::Result<std::path::PathBuf> {
    let dir = match db::downloads_dir() {
        Some(d) => d,
        None => {
            let d = db::app_data_dir().join("exports");
            std::fs::create_dir_all(&d)?;
            d
        }
    };
    let path = dir.join(format!("relay-diagnostics-{stamp}.md"));
    // `db` is the ONLY module allowed to read HOME/APPDATA (rule 9, and
    // `db::path_rule` fails the build if this is re-derived here). Every caller that
    // reached for HOME directly got Windows wrong.
    let home = db::home_dir();
    std::fs::write(&path, scrub_paths(body, home.as_deref()))?;
    Ok(path)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn f(k: &str, v: &str) -> Fact {
        Fact::new(k, v)
    }

    #[test]
    fn the_home_directory_is_replaced_everywhere_it_appears() {
        let text = "model at /Users/ada/Library/App/model.bin and db at /Users/ada/relay.db";
        let out = scrub_paths(text, Some("/Users/ada"));
        assert!(!out.contains("ada"), "{out}");
        assert_eq!(out, "model at ~/Library/App/model.bin and db at ~/relay.db");
    }

    #[test]
    fn a_windows_home_is_scrubbed_in_either_separator() {
        let text = r"db at C:\Users\Ada\AppData\relay.db and C:/Users/Ada/AppData/x";
        let out = scrub_paths(text, Some(r"C:\Users\Ada"));
        assert!(!out.contains("Ada"), "{out}");
    }

    /// A SHORT OR MISSING HOME IS NOT A LICENCE TO MANGLE THE FILE.
    ///
    /// `HOME=/` would otherwise replace every slash in the document with a tilde.
    #[test]
    fn a_useless_home_value_changes_nothing() {
        let text = "a/b/c";
        assert_eq!(scrub_paths(text, None), text);
        assert_eq!(scrub_paths(text, Some("/")), text);
        assert_eq!(scrub_paths(text, Some("")), text);
    }

    #[test]
    fn the_bundle_says_up_front_what_it_does_not_contain() {
        // The first thing a church reads. Somebody deciding whether to send this
        // file needs the answer before the facts, not after them.
        let md = compose(&[("Relay", vec![f("Version", "0.1.0-4")])]);
        let head = &md[..md.find("## Relay").unwrap()];
        assert!(head.contains("no transcript"));
        assert!(head.contains("no verse text"));
        assert!(head.contains("belongs to your church"));
    }

    #[test]
    fn an_empty_section_says_so_rather_than_vanishing() {
        // A missing section reads as "Relay did not check that". An empty one reads
        // as "there was nothing", which is the truth.
        let md = compose(&[("Screens", vec![])]);
        assert!(md.contains("## Screens"));
        assert!(md.contains("_Nothing to report._"));
    }

    #[test]
    fn it_tells_the_operator_not_to_edit_it() {
        let md = compose(&[("Relay", vec![f("Version", "0.1.0-4")])]);
        assert!(md.contains("editing it usually removes the part that explains the problem"));
    }
}
