-- ─────────────────────────────────────────────────────────────────────────────
-- THE OLDEST SCHEMA RELAY CAN UPGRADE FROM. DO NOT EDIT THIS FILE.
--
-- This is `docs/data/schema.sql` as it stood at the first commit that had one
-- (a35d7d2, "Phase 0: green baseline"). It is checked in for exactly one reason:
-- so a test can diff today's schema against it and prove that **every column
-- added since has a migration** that reaches a database created back then.
--
-- Without it that half could not be checked. `db::mod.rs`'s
-- `every_column_an_upgrade_adds_reaches_a_database_that_predates_it` can only
-- verify the migrations that EXIST actually run; it cannot notice one that was
-- never written, because there is nothing to find. This file is the missing
-- other side of that comparison, and RG-56 was recorded as unclosable for the
-- want of it — wrongly, because git had it all along.
--
-- Editing this to make a test pass would be editing the past. If a column is
-- genuinely new, give it an `ALTER TABLE … ADD COLUMN` behind a pragma sniff
-- (CLAUDE.md rule 25) — that is what the test is asking for.
-- ─────────────────────────────────────────────────────────────────────────────

-- Relay — SQLite schema (v0.1 draft)
-- Local-first. Every table lives on-device by default.

PRAGMA foreign_keys = ON;

-- ===== Reference data =====

CREATE TABLE translations (
    id            INTEGER PRIMARY KEY,
    name          TEXT NOT NULL,          -- e.g. "King James Version"
    abbreviation  TEXT NOT NULL,          -- e.g. "KJV"
    language      TEXT NOT NULL,          -- ISO 639-1/3 code, e.g. "en", "yo", "sw", "ha"
    license_type  TEXT                    -- public domain / licensed, etc.
);

CREATE TABLE verses (
    id             INTEGER PRIMARY KEY,
    translation_id INTEGER NOT NULL REFERENCES translations(id),
    book           TEXT NOT NULL,         -- canonical book name
    chapter        INTEGER NOT NULL,
    verse          INTEGER NOT NULL,
    text           TEXT NOT NULL,
    embedding      BLOB                   -- precomputed vector for semantic match, nullable until indexed
);
CREATE INDEX idx_verses_lookup ON verses(translation_id, book, chapter, verse);

-- ===== Presentation =====

CREATE TABLE templates (
    id                 INTEGER PRIMARY KEY,
    name               TEXT NOT NULL,
    region_config_json TEXT NOT NULL,     -- layout regions, see docs/SPEC.md §5
    style_json         TEXT NOT NULL      -- fonts, colors, transitions
);

CREATE TABLE output_channels (
    id             INTEGER PRIMARY KEY,
    name           TEXT NOT NULL,
    render_target  TEXT NOT NULL CHECK (render_target IN ('native_window', 'ndi_encode', 'network_client')),
    template_id    INTEGER REFERENCES templates(id),
    display_target TEXT,                  -- display index, NDI source name, or kiosk client id
    status         TEXT NOT NULL DEFAULT 'offline' CHECK (status IN ('online', 'offline'))
);

-- ===== Live session data =====

CREATE TABLE services (
    id    INTEGER PRIMARY KEY,
    date  TEXT NOT NULL,                  -- ISO 8601 date
    title TEXT NOT NULL
);

CREATE TABLE transcripts (
    id         INTEGER PRIMARY KEY,
    service_id INTEGER NOT NULL REFERENCES services(id),
    timestamp  REAL NOT NULL,             -- seconds since service start
    text       TEXT NOT NULL,
    language   TEXT NOT NULL,             -- detected language for this chunk
    confidence REAL                       -- STT confidence, 0-1
);

CREATE TABLE detections (
    id            INTEGER PRIMARY KEY,
    transcript_id INTEGER NOT NULL REFERENCES transcripts(id),
    verse_id      INTEGER REFERENCES verses(id),
    method        TEXT NOT NULL CHECK (method IN ('direct', 'semantic')),
    confidence    REAL NOT NULL,
    status        TEXT NOT NULL CHECK (status IN ('auto', 'suggested', 'dismissed')),
    fired_at      REAL                    -- seconds since service start, null if never fired
);

CREATE TABLE cues (
    id           INTEGER PRIMARY KEY,
    service_id   INTEGER NOT NULL REFERENCES services(id),
    type         TEXT NOT NULL,           -- e.g. "manual_override", "clear_screens", "template_change"
    payload_json TEXT,
    triggered_at REAL NOT NULL
);
